FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env

RUN sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d

WORKDIR /App

COPY . ./

RUN task solution:publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0

WORKDIR /App

COPY --from=build-env /App/src/Effuse.Server.Local/bin/Release/net8.0 .

ENV APP_PREFIX server
ENV DATA_DIR /data

ENV SSO_BASE_URL https://effuse-sso.taylorhousehold.uk/

EXPOSE 3002

ENTRYPOINT ["./docker-scripts/start-server.sh"]