FROM mcr.microsoft.com/dotnet/sdk:8.0

RUN sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d

WORKDIR /App

COPY . ./

RUN apt update
RUN apt install nodejs -y

ENTRYPOINT ["task", "pipeline:run"]